#' ECDF ggplot
#'
#' Draw the step-curve corresponging to the
#' Empirical Cumulative Distribution Function's result from [stat_ecdf_data()].
#'
#' @param data (`data.frame`)\cr as generated by [stat_ecdf_data()].
#' @param xlab (`character`)
#' @param watermark (`character`)\cr no watermark added if `NUll`.
#'
#' @details The function [ggplot2::stat_ecdf()] could be used and provide the
#' same results. However, a plotly representation is also demanded, and
#' the conversion from the `ggplot2` using `stat_ecdf` to `plotly` using
#' [plotly::ggplotly()] is not working. This function relies on a simpler
#' function, [ggplot2::geom_step()], which works straightforwardly with
#' [plotly::ggplotly()] conversion.
#'
#' @import ggplot2
#' @export
#' @examples
#'
#' df <- by(
#'   data = iris,
#'   INDICES = list(iris$Species), FUN = function(x) {
#'     df <- stat_ecdf_data(
#'       x$Sepal.Length,
#'       xout = unique(iris$Sepal.Length)
#'     )
#'     df$grp <- unique(x$Species)
#'     df
#'   })
#' df <- do.call(rbind, df)
#' gg_ecdf(df, watermark = NULL)
#'
gg_ecdf <- function(data,
                    xlab = NULL,
                    watermark = control()$watermark) {
  gg <- ggplot(
    data = data,
    mapping = aes_string(
      x = "x",
      y = "y",
      color = "grp"
    )
  ) + geom_step(
  ) + scale_color_manual(
    values = c("#BCBCBC", "#EE8000", "#CF004D", "#354B96", "#4EADD0", "#884FA0")
  ) + scale_y_continuous(
    labels = function(x) paste0(x, "%")
  ) + scale_x_continuous(
    breaks = c(0, seq_len(10))
  ) + xlab(
    xlab
  ) + ylab(
    "Cumulative percentage"
  ) + theme_minimal(
  ) + theme(
    axis.line = ggplot2::element_line(colour = "black"),
    axis.ticks = element_line(colour = "black"),
    legend.title = element_blank(),
    legend.justification = "top",
    legend.key.height = grid::unit(2, "lines"),
    panel.grid.minor = ggplot2::element_blank(),
    panel.grid.major = ggplot2::element_blank(),
    text = element_text(size = 9)
  )

  if (!is.null(watermark)) {
    gg + annotate(
      geom = "text", x = -Inf, y = Inf,
      hjust = "left", vjust = "top",
      label = watermark, color = "gray45",
      fontface = "bold", size = 6,
      alpha = 0.5
    )
  } else {
    gg
  }
}

#' Plotly sections
#'
#' Transform the step-curve to plotly outputs with markdown/html decoration
#' annotation. This is a study specific function.
#'
#' @param x (`list`)\cr includes the ggplot as an object and v
#' @param ctrl (`character`)\cr controls as managed with [control()].
#'
#' @importFrom plotly ggplotly add_annotations layout
#' @importFrom htmlwidgets saveWidget
#' @export
#'
plotly_sections <- function(x,
                            ctrl = control()) {
  cat("## ", x$annot$num, x$param, "\n\n")

  file <- file.path(ctrl$tmp_dir_bkz, x$html) # TODO # rm

  if (!dir.exists(dirname(file))) {
    dir.create(dirname(file), recursive = TRUE)
  }

  df <- x$data_plot
  x$annot$str_width <- 80
  x$annot <- do.call(annotation_g2p, x$annot)
  p <- ecdf_plotly(
    x = df$x,
    y = df$y,
    grp = df$grp,
    text = paste0(df$y, "%"),
    title = x$annot$title[seq_len(2)],
    xlab = x$param,
    colors = c(
      "#BCBCBC", "#EE8000", "#CF004D", "#354B96", "#4EADD0", "#884FA0"),
    gxp_annot = list(
      label = "GxP Info",
      text = paste(
        paste(c(x$annot$header_left, x$annot$header_right), collapse = " - "),
        "Title:",
        paste(
          strwrap(paste(x$annot$title, collapse = "\n"), width = 80),
          collapse = "<br>"
        ),
        "Acronym & Note:",
        paste(x$annot$note, collapse = "\n"),
        paste(x$annot$footer_left, collapse = " - "),
        sep = "<br>"
      )
    )
  )

  htmlwidgets::saveWidget(
    p,
    file = file.path(file),
    selfcontained = FALSE, libdir = "lib"
  )

  cat(
    "<div><iframe src=\"",
    x$html,
    "\" width=\"672\" height=\"400px\"></iframe></div>\n\n",
    sep = ""
  )
  cat(
    "<div><p>This is an interactive representation of the figure ",
    "<a href=\"pdf/", basename(x$pdf), "\" target = \"_blank\">",
    basename(x$pdf), "</a>. ",
    "Open the interactive figure in a ",
    "<a href=\"", x$html, "\" target = \"_blank\">new tab</a>.</div>\n\n",
    sep = ""
  )
}

#' ECDF Plotly
#'
#' Template to render the ECDF function with plotly
#'
#' @param x,y (`numeric`)\cr x and y axis values.
#' @param grp (`factor`)\cr mapped to colors.
#' @param text (`character`)\cr displayed on data hovering.
#' @param colors (`character`)\cr colors for the series.
#' @param title (`character`)
#' @param xlab,ylab (`character`)\cr axis labels.
#' @param gxp_annot (`list`)\cr with item label (displayed within
#'   graphic) and text (displayed on hovering).
#'
#' @importFrom plotly plot_ly add_annotations layout config
#' @export
#' @examples
#'
#' df <- by(
#'   data = iris,
#'   INDICES = list(iris$Species), FUN = function(x) {
#'     df <- stat_ecdf_data(
#'       x$Sepal.Length,
#'       xout = unique(iris$Sepal.Length)
#'     )
#'     df$grp <- unique(x$Species)
#'     df
#'   })
#' df <- do.call(rbind, df)
#' df$y <- df$y * 100
#' df$text <- paste0(df$y, "%")
#' gg_ecdf(df, watermark = NULL)
#' fig <- ecdf_plotly(
#'   x = df$x,
#'   y = df$y, grp = df$grp, text = df$text,
#'   colors = c(
#'     virginica = "#BCBCBC", versicolor = "#EE8000", setosa = "#CF004D"
#'   )
#' )
#' fig
#'
ecdf_plotly <- function(x,
                        y,
                        grp,
                        text,
                        colors = NULL,
                        title = "A title",
                        xlab = "",
                        ylab = "Cumulative percentage",
                        gxp_annot = list(
                          label = "info",
                          text = NULL
                        )
) {

  df <- data.frame(
    x = x,
    y = y,
    text = text
  )

  p <- plotly::plot_ly(
    data = df,
    x = ~ x, y = ~ y,
    color = ~ grp,
    text = ~ text,
    colors = colors,
    hoverinfo = "x+text",
    type = "scatter", mode = "lines",
    line = list(shape = "hv")
  )

  if (!is.null(gxp_annot$text)) {
    p <- plotly::add_annotations(
      p = p,
      text = gxp_annot$label,
      y = min(y), x = max(x),
      font = list(color = "gray", size = 15),
      showarrow = FALSE,
      xref = "x",
      yref = "y",
      xanchor = "right",
      yanchor = "bottom",
      hovertext = gxp_annot$text
    )
  }

  if (!is.null(title)) {
    title <- strwrap(paste(title, collapse = " "), width = 70)
    p <- plotly::layout(
      p = p,
      title = paste(title, collapse = "\n"),
      font = list(size = 9)
    )
  }

  xaxis <- list(
    showspikes = TRUE,
    spikecolor = "gray",
    spikethickness = 1.5,
    spikedash = "solid",
    spikemode = "across",
    spikesnap = "cursor",
    showgrid = FALSE,
    tickvals = 0:10,
    ticktext = 0:10
  )

  if (!is.null(xlab)) xaxis$title <- xlab
  p <- plotly::layout(
    p,
    hovermode = "x unified",
    spikedistance = -1,
    xaxis = xaxis,
    yaxis = list(
      tickvals = seq(0, 100, 20),
      ticktext = paste0(seq(0, 100, 20), "%"),
      title = ylab
    )
  )

  plotly::config(
    p,
    displaylogo = FALSE,
    collaborate = FALSE,
    modeBarButtonsToRemove = c(
      "zoomIn2d", "zoomOut2d", "toImage", "toggleSpikelines"
    )
  )
}
