languageCode: en-us
title: Portfolio
theme: hugo-theme-learn
publishDir: docs

relativeURLs: true
uglyURLs: true
pluralizelisttitles: false

# For search functionality
outputs:
  home: ["HTML", "RSS", "JSON"]

params:
  themeVariant: green


