---
title: "Utils"
subtitle: ""
author: "FCA Collin, Ph.D."
date: "`r format(Sys.Date(), '%A, %B %d, %Y')`"
weight: -210311
---

_2021-03-19, FCA Collin_

---

<!--more-->
```{r setup_knitr, echo = FALSE, message = FALSE, warning = FALSE}
fig.height <- 5;
fig.width <- 16/9 * fig.height;
knitr::opts_chunk$set(
  fig.width  = fig.width,
  fig.height = fig.height,
  dev = c('png', 'pdf', 'svg'),
  fig.path = "img/"
)
```

## Dummy var

```{r}
#' Dummy Variable
#'
#' Decompose a factor-coercible variable into dummy variables.
#' 
#' @param x (`atomic`)
#' @export
#' @source <https://fcacollin.github.io/guide/utils_01/utils_01.html>
#' @md
#' @examples
#' # Use case data.frame.
#' head(iris)
#' head(dummy_var(iris$Species))
#' iris$sp <- dummy_var(iris$Species)
#' head(iris)
#' 
#' # With logical.
#' dummy_var(c(TRUE, FALSE))
#' 
#' # With character.
#' dummy_var(c("cat", "cat", "dog", "corgi", "corgi"))
#' 
dummy_var <- function(x) {
  stopifnot(is.atomic(x))
  if (!is.factor(x)) {
    x <- as.factor(x)
  }
  x <- droplevels(x)
  y <- stats::model.matrix(~ x + 0)
  colnames(y) <- levels(x)
  as.data.frame(y)
}

```

```{r}
# Use case data.frame.
head(iris)
head(dummy_var(iris$Species))
iris$sp <- dummy_var(iris$Species)
head(iris)

# With logical.
dummy_var(c(TRUE, FALSE))

# With character.
dummy_var(c("cat", "cat", "dog", "corgi", "corgi"))

```

## Matrix To Long Format

```{r}
#' Matrix-like Data To Long Data Frame
#'
#' Transform a matrix-like data set into a long data frame.
#'
mat_to_long_df <- function(x, ...) {
  UseMethod("mat_to_long_df", x)
}

mat_to_long_df.matrix <- function(x, names = c("row", "col", "value"), ...) {
  
  assertthat::assert_that(length(names) == 3L)
  if (is.null(colnames(x))) colnames(x) <- as.character(seq_len(ncol(x)))
  if (is.null(rownames(x))) rownames(x) <- as.character(seq_len(nrow(x)))

  y <- data.frame(
    rownames(x)[c(row(x))],
    colnames(x)[c(col(x))],
    c(x),
    row.names = NULL
  )

  names(y) <- names
  y
}

mat_to_long_df.data.frame <- function(x, ...) {
  x <- as.matrix(x)
  mat_to_long_df(x, ...)
}

m <- matrix(
   c(
    11, 12,
    21, 22,
    31, 32
    ),
  nrow = 3, byrow = TRUE,
  dimnames = list(row = 1:3, col = 1:2)
)
df <- as.data.frame(m)

mat_to_long_df(m)
mat_to_long_df(df)

```

```{r}
library(testthat)
test_that("mat_to_long_df names are used", {
  result <- mat_to_long_df(m, names = c("a", "b", "y"))
  expected <- data.frame(
    a = c("1", "2", "3", "1", "2", "3"),
    b = c("1", "1", "1", "2", "2", "2"),
    y = c(11, 21, 31, 12, 22, 32)
  )
  expect_identical(result, expected)
})

test_that("mat_to_long_df error if not 3 names provided", {
  expect_error(mat_to_long_df(m, names = "a"))
})
```

## Set a theme for `ggplot2`

```{r}
#' `ggplot` theme
#'
#' Compliance with journal requirements.
#' @param reset (`flag`).
#' @export
#'
theme_rpack <- function(reset = FALSE) {

  assertthat::assert_that(is.logical(reset))
  if (reset) {
    ggplot2::theme_set(ggplot2::theme_gray())
  } else {
    new_theme <- ggplot2::theme_minimal() +
      ggplot2::theme(
        line = ggplot2::element_line(color = "black"),
        legend.position = "bottom",
        legend.key.height = grid::unit(.3, "cm"),
        text = ggplot2::element_text(size = 8),
        plot.margin = ggplot2::margin(0, 0, 0, 0, "cm"),
        legend.margin = ggplot2::margin(0, 0, 0, 0, "cm")
      )
    ggplot2::theme_set(new_theme)
  }
}
```

```{r, fig.width = 7, height = 3}
library(ggplot2)
gg <- ggplot(economics, aes(date, unemploy)) + geom_line()
gg
```

```{r, fig.width = 7, height = 3}
theme_rpack()
gg
```

```{r, fig.width = 7, height = 3}
theme_rpack(reset = TRUE)
gg
```


##

```{r}
sessionInfo()
```

[modeline]: # ( vim: set foldlevel=0 spell spelllang=en_gb: ) 
